### ISSUE TITLE
npx vite build erroring out over tailwinds-safe-area

### ISSUE THREAD

**Issue by AELovelace** [eilefsen/dotify#2]
i finally got to pushing newest dotify to my server and im running into a vite build issue. it's probably something with my build environment but google isn't helping me with this one. this is what it's spitting at me:

┌──(aedith㉿TRSHPNCSS-2)-[~/dotify/frontend]
└─$ npx vite build

♻️  Generating routes...
✅ Processed routes in 193ms
vite v5.2.10 building for production...
✓ 7 modules transformed.
x Build failed in 119ms
error during build:
Error: [vite-plugin-pwa:build] [postcss] Cannot find module 'tailwindcss-safe-area'
Require stack:
- /home/aedith/dotify/frontend/tailwind.config.js
file: /home/aedith/dotify/frontend/src/index.css:undefined:NaN
    at Module._resolveFilename (node:internal/modules/cjs/loader:1202:15)
    at Function.resolve (node:internal/modules/helpers:199:19)
    at _resolve (/home/aedith/dotify/frontend/node_modules/jiti/dist/jiti.js:1:251148)
    at jiti (/home/aedith/dotify/frontend/node_modules/jiti/dist/jiti.js:1:253746)
    at /home/aedith/dotify/frontend/tailwind.config.js:93:3
    at evalModule (/home/aedith/dotify/frontend/node_modules/jiti/dist/jiti.js:1:256443)
    at jiti (/home/aedith/dotify/frontend/node_modules/jiti/dist/jiti.js:1:254371)
    at /home/aedith/dotify/frontend/node_modules/tailwindcss/lib/lib/load-config.js:48:30
    at loadConfig (/home/aedith/dotify/frontend/node_modules/tailwindcss/lib/lib/load-config.js:50:6)
    at getTailwindConfig (/home/aedith/dotify/frontend/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:71:116)

here's my npm version if that helps

┌──(aedith㉿TRSHPNCSS-2)-[~]
└─$ npm version
{
  npm: '10.5.1',
  node: '22.0.0',
  acorn: '8.11.3',
  ada: '2.7.7',
  ares: '1.28.1',
  base64: '0.5.2',
  brotli: '1.1.0',
  cjs_module_lexer: '1.2.2',
  cldr: '44.1',
  icu: '74.2',
  llhttp: '9.2.1',
  modules: '127',
  napi: '9',
  nghttp2: '1.61.0',
  nghttp3: '0.7.0',
  ngtcp2: '1.3.0',
  openssl: '3.0.13+quic',
  simdjson: '3.8.0',
  simdutf: '5.2.4',
  tz: '2024a',
  undici: '6.11.1',
  unicode: '15.1',
  uv: '1.48.0',
  uvwasi: '0.0.20',
  v8: '12.4.254.14-node.10',
  zlib: '1.3.0.1-motley-24c07df'
}

Probably missing something simple. I'm pretty new to this stuff. 
Thx <3

**Comment by eilefsen** [comment]
The error says youre missing a plugin for tailwind. 

The plugin was added to package.json in a [recent commit](https://github.com/eilefsen/dotify/commit/57971fba916814c45c9052608389eabf48a9805f).

package.json is where project dependencies are specified. and they are installed with the command `npm install`

my guess is that you didnt run `npm install` before attempting to build, therefore your local copy does not have the new required dependencies introduced between your old version and latest.

run `npm install`, and then try building again. let me know what happens. :)

**Comment by AELovelace** [comment]
I triple checked my terminal history and I definitely ran npm install before npx vite build. It returns a different error if I don't run npm install first.

________________________________

**Comment by eilefsen** [comment]
huh, interesting. could you give me the output of `npm ls`? and could you briefly try running `npm run vite build` instead of the equivalent npx? i'll try and build a fresh clone later today and see if i can replicate it myself.

**Comment by AELovelace** [comment]
sorry for the late reply. here is npm ls

┌──(aedith㉿TRSHPNCSS-2)-[~/dotify/frontend]
└─$ npm ls
dotify@0.0.0 /home/aedith/dotify/frontend
├── @hookform/resolvers@3.3.4
├── @radix-ui/react-accordion@1.1.2
├── @radix-ui/react-context-menu@2.1.5
├── @radix-ui/react-dialog@1.0.5
├── @radix-ui/react-dropdown-menu@2.0.6
├── @radix-ui/react-icons@1.3.0
├── @radix-ui/react-label@2.0.2
├── @radix-ui/react-popover@1.0.7
├── @radix-ui/react-progress@1.0.3
├── @radix-ui/react-select@2.0.0
├── @radix-ui/react-slider@1.1.2
├── @radix-ui/react-slot@1.0.2
├── @radix-ui/react-toggle@1.0.3
├── @tanstack/react-query@5.28.9
├── @tanstack/react-router@1.29.2
├── @tanstack/router-devtools@1.29.2
├── @tanstack/router-vite-plugin@1.30.0
├── @types/node@20.11.6
├── @types/react-dom@18.2.18
├── @types/react@18.2.48
├── @typescript-eslint/eslint-plugin@6.19.1
├── @typescript-eslint/parser@6.19.1
├── @vitejs/plugin-react-swc@3.5.0
├── autoprefixer@10.4.17
├── axios@1.6.8
├── class-variance-authority@0.7.0
├── clsx@2.1.1
├── eslint-plugin-react-hooks@4.6.0
├── eslint-plugin-react-refresh@0.4.5
├── eslint@8.56.0
├── lucide-react@0.373.0
├── mobx-react-lite@4.0.5
├── postcss@8.4.38
├── prettier-plugin-tailwindcss@0.5.12
├── prettier@3.2.5
├── react-device-detect@2.2.3
├── react-dom@18.2.0
├── react-hook-form@7.51.3
├── react-icons@5.0.1
├── react-use@17.5.0
├── react@18.2.0
├── tailwind-extended-shadows@0.4.0
├── tailwind-merge@2.3.0
├── tailwindcss-animate@1.0.7
├── tailwindcss@3.4.1
├── typescript@5.3.3
├── vaul@0.9.0
├── vite-plugin-pwa@0.19.8
├── vite@5.2.10
└── zod@3.23.5

npm run vite build returns this

┌──(aedith㉿TRSHPNCSS-2)-[~/dotify/frontend]
└─$ npm run vite build
npm ERR! Missing script: "vite"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: /home/aedith/.npm/_logs/2024-07-20T20_49_44_624Z-debug-0.log

**Comment by eilefsen** [comment]
im really confused as to how this happened, but the plugin was removed at some point from package.json between now and the linked commit. its been added back in, try the latest commits now `git pull && npm i && npx vite build`

**Comment by eilefsen** [comment]
ah.... that package was added from the cli while in the wrong directory. so there was two package.json files. i have resolved that.

**Comment by eilefsen** [comment]
let me know in case something else is broken. if its related to this issue i will reopen. otherwise submit a new issue.
